version: '3.4'

services:
  githubactionsdockerdemo:
    image: githubactionsdockerdemo
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
