name: CI-CD
on:
  push:
    branches: [main]
jobs:
  push_to_Docker_Hub:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets. DOCKERHUB_USERNAME }}
          password: ${{ secrets. DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ankitbhojani/awsdemo:latest
  run_on_container:
    runs-on: ubuntu-latest
    needs: [push_to_Docker_Hub]
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          image: ankitbhojani/awsdemo:latest
          script: |
            #remove docker container which are running
            docker rm -f $(docker ps -a -q)
            #pull docker image if any changes
            docker pull ankitbhojani/awsdemo:latest
            #run new docker container
            docker run --name deploydocker -d -p 3000:3000 ankitbhojani/awsdemo:latest
            exit
